name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & deploy
        run: docker compose up -d --build --force-recreate

      - name: Cleanup old images
        run: docker image prune -f